version: '3.8'
services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./Simhastha_Complete_Dataset.csv:/app/../Simhastha_Complete_Dataset.csv

  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/api/v1/stream
    ports:
      - "3000:3000"
    depends_on:
      - backend
